FROM python:3.11-slim
WORKDIR /app

# Install curl for healthchecks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copy pyproject.toml and source code
COPY pyproject.toml /app/
COPY mock_service /app/mock_service

# Install package and dependencies
RUN pip install --no-cache-dir .

CMD ["uvicorn","mock_service.app:app","--host","0.0.0.0","--port","8000"]
